// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9e5vcxtma4Qaa6QeltoQxgcF4uVa65t0',
    appId: '1:192451838179:web:37e156a7c40c67756d85d6',
    messagingSenderId: '192451838179',
    projectId: 'tuteflutter',
    authDomain: 'tuteflutter.firebaseapp.com',
    storageBucket: 'tuteflutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5G7-OuYCfUSWfze2xPeOQMT7LwkRfpgo',
    appId: '1:192451838179:android:eb1abea72d0b61466d85d6',
    messagingSenderId: '192451838179',
    projectId: 'tuteflutter',
    storageBucket: 'tuteflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8HhXsq6Oq4QG7RuqCjh35dGaGAOQkDx0',
    appId: '1:192451838179:ios:cfe0db3ae169b9fe6d85d6',
    messagingSenderId: '192451838179',
    projectId: 'tuteflutter',
    storageBucket: 'tuteflutter.appspot.com',
    iosBundleId: 'com.example.flutterTute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8HhXsq6Oq4QG7RuqCjh35dGaGAOQkDx0',
    appId: '1:192451838179:ios:dbcfdc836273b4ab6d85d6',
    messagingSenderId: '192451838179',
    projectId: 'tuteflutter',
    storageBucket: 'tuteflutter.appspot.com',
    iosBundleId: 'com.example.flutterTute.RunnerTests',
  );
}
